# Generated by Django 2.1.4 on 2019-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
