# Generated by Django 3.2.4 on 2021-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(0, 'First'), (1, 'Second'), (2, 'Third'), (3, 'Fourth'), (4, 'Fifth')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Very Hard'), (4, 'Advanced')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Objective'), (1, 'Subjective'), (2, 'Theory')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Class Work'), (1, 'Home Work'), (2, 'Class Test'), (3, 'Exam')], default=None, null=True),
        ),
    ]
