# Generated by Django 3.2.4 on 2021-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='subjects',
            field=models.ManyToManyField(to='school.Subject'),
        ),
    ]
