# Generated by Django 3.2.4 on 2021-06-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_session_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
    ]
