# Generated by Django 3.2.4 on 2021-06-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.employer'),
        ),
    ]
