# Generated by Django 2.1.4 on 2019-01-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
