# Generated by Django 2.1.4 on 2019-01-08 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Expiry',
        ),
    ]
