# Generated by Django 2.1.4 on 2019-01-05 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
