# Generated by Django 2.1.4 on 2019-01-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('for_primary', models.BooleanField(default=False)),
                ('for_secondary', models.BooleanField(default=False)),
            ],
        ),
    ]
