# Generated by Django 2.1.4 on 2019-01-05 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assignments/')),
                ('stage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
            ],
        ),
    ]
